<#
.SYNOPSIS
  Runs the Flutter app against the DEV Supabase backend (poll-social-app-dev).

.PARAMETER Release
  Run in release mode instead of the default debug mode.

.PARAMETER Device
  Flutter device id to target, e.g. "windows", "chrome" (passed through as -d).

.PARAMETER WebPort
  Fixes the web dev server to this port (passed through as --web-port). Use
  9555 to match AppConfig.publicShareBaseUrl's default, so share links
  generated by this instance are openable in another tab/window/browser on
  this machine (flutter run's default web port is otherwise random per run).

.EXAMPLE
  .\scripts\run_dev.ps1
  .\scripts\run_dev.ps1 -Release -Device windows
  .\scripts\run_dev.ps1 -Device chrome -WebPort 9555
#>
param(
    [switch]$Release,
    [string]$Device,
    [int]$WebPort
)

$SupabaseUrl = "https://uwomsxkvjqrvhdpnbkit.supabase.co"
$SupabaseAnonKey = "sb_publishable_LgwGHGciORtyBWVRajywqA_JYzCokcF"

$flutterArgs = @(
    "run",
    "--dart-define=APP_ENV=dev",
    "--dart-define=SUPABASE_URL=$SupabaseUrl",
    "--dart-define=SUPABASE_ANON_KEY=$SupabaseAnonKey"
)

if ($Release) { $flutterArgs += "--release" }
if ($Device) { $flutterArgs += @("-d", $Device) }
if ($WebPort) { $flutterArgs += @("--web-port", $WebPort) }

& flutter @flutterArgs
